import Head from "next/head"
import MainPage from "../components/Main/MainPage"
import { useMoralis } from "react-moralis"
import Exclamation from "../components/Layout/Exclamation"

export default function Home() {
    const { isWeb3Enabled } = useMoralis()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {isWeb3Enabled ? (
                    <div>
                        <MainPage />
                    </div>
                ) : (
                    <Exclamation msg="enable web3" />
                )}
            </main>
        </>
    )
}
